# Generated by Django 5.1 on 2024-09-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asdf", "0009_alter_users_money"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="money",
        ),
        migrations.RemoveField(
            model_name="users",
            name="sword_level",
        ),
        migrations.AddField(
            model_name="users",
            name="address",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="users",
            name="address_detail",
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="users",
            name="phone",
            field=models.CharField(default=3, max_length=15),
            preserve_default=False,
        ),
    ]
