# Generated by Django 5.1 on 2024-09-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asdf", "0010_remove_users_money_remove_users_sword_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="location",
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="posts",
            name="location_detail",
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
