# Generated by Django 5.1 on 2024-10-02 06:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asdf", "0011_posts_location_posts_location_detail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messages",
            name="connected_user",
        ),
        migrations.RemoveField(
            model_name="messages",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="messages",
            name="title",
        ),
        migrations.AddField(
            model_name="messages",
            name="connected_post",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="asdf.posts",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="messages",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="messages",
            name="user",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="posts",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="posts",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
