# Generated by Django 5.1 on 2024-10-02 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asdf", "0012_remove_messages_connected_user_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Messages",
            new_name="Comment",
        ),
    ]
